### ISSUE TITLE
Date error when editing older play

### ISSUE THREAD

**Issue by jeep** [LaxZap91/Slots#20]
When editing a previous play, this error occurs:
```
PS C:\Users\jeepe\dev\Slots>  c:; cd 'c:\Users\jeepe\dev\Slots'; & 'c:\Users\jeepe\dev\Slots\.venv\Scripts\python.exe' 'c:\Users\jeepe\.vscode\extensions\ms-python.debugpy-2024.6.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher' '59565' '--' 'C:\Users\jeepe\dev\Slots\Programs\threaded_main.py' 
Loading  2024-08-09 07:28:01.457676
Loaded  2024-08-09 07:28:01.477676
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\jeepe\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1968, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\jeepe\dev\Slots\Programs\Scripts\ImageButtons.py", line 32, in <lambda>
    self.save_button    = ttk.Button(self, text='Save Play', command=lambda: self._window.save(), bootstyle='success')
                                                                             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeepe\dev\Slots\Programs\threaded_main.py", line 427, in save
    self.update_all_play_values()
  File "C:\Users\jeepe\dev\Slots\Programs\threaded_main.py", line 394, in update_all_play_values
    self.update_session_date()
  File "C:\Users\jeepe\dev\Slots\Programs\threaded_main.py", line 249, in update_session_date
    self._current_play.session_date = datetime.datetime.strptime(
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeepe\AppData\Local\Programs\Python\Python312\Lib\_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jeepe\AppData\Local\Programs\Python\Python312\Lib\_strptime.py", line 333, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2024-06-01' does not match format '%Y%m%d'
```

**Comment by jeep** [comment]
Fixed with next PR
